[package]
name = "kashimark"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.11"
fw-conv.git = "https://github.com/crumblingstatue/fw-conv.git"

[dev-dependencies]
clap.version = "4.5.30"
clap.features = ["derive"]
